# Generated by Django 6.0.1 on 2026-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['autor'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('idioma', models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español'), ('DE', 'Alemán'), ('FR', 'Francés'), ('PT', 'Portugués'), ('IT', 'Italiano')], max_length=2)),
                ('autores', models.ManyToManyField(related_name='libros', to='core.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['titulo'],
            },
        ),
    ]
