# Generated by Django 6.0.1 on 2026-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nacionalidad_autor_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(default=0, verbose_name='páginas'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
    ]
