# Generated by Django 6.0.1 on 2026-02-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libro_paginas_alter_autor_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['idioma', 'titulo'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
    ]
